### ISSUE TITLE
problem with rake first run

### ISSUE THREAD

**Issue by hun7er** [realloc/chef-cuisine#2]
$ rake
rake aborted!
LoadError: cannot load such file -- chef/role
/Users/hun7er/Development/realloc/chef-cuisine/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by hun7er** [comment]
Chef Development Kit Version: 0.6.2
chef-client version: 12.3.0
berks version: 3.2.3
kitchen version: 1.4.0
packer v0.7.5
vagrant 1.7.2
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

**Comment by realloc** [comment]
use `chef exec rake`
